MicroFocus/octane-ci-java-sdk

integrations-dto/pom.xml, integrations-sdk/pom.xml, pom.xml
- Integrate sonatype deployment
- pom alignments
=> Integrate sonatype deployment

integrations-dto/src/main/java/com/hp/octane/integrations/dto/executor/DiscoveryInfo.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/executor/TestSuiteExecutionInfo.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/executor/impl/DiscoveryInfoImpl.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/executor/impl/TestSuiteExecutionInfoImpl.java, integrations-dto/src/test/java/com/hp/octane/integrations/dto/executor/ExecutorDTOTests.java, integrations-sdk/src/main/java/com/hp/octane/integrations/services/tasking/TasksProcessorImpl.java, integrations-sdk/src/main/java/com/hp/octane/integrations/spi/CIPluginServices.java, integrations-sdk/src/main/java/com/hp/octane/integrations/spi/CIPluginServicesBase.java
1.supporting  deleteSuite/deleteExecutor in ciServerApi
2.supporting scmRepositoryCredentialsId in discoveryInfo and executionInfo for git repository
=> Support deleteSuite/Executor and adding credentials for git repository

integrations-dto/src/main/java/com/hp/octane/integrations/dto/executor/CredentialsInfo.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/executor/DiscoveryInfo.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/executor/TestConnectivityInfo.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/executor/TestExecutionInfo.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/executor/TestSuiteExecutionInfo.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/executor/impl/CredentialsInfoImpl.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/executor/impl/DTOExecutorsProvider.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/executor/impl/DiscoveryInfoImpl.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/executor/impl/TestConnectivityInfoImpl.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/executor/impl/TestExecutionInfoImpl.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/executor/impl/TestSuiteExecutionInfoImpl.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/executor/impl/TestingToolType.java, integrations-dto/src/test/java/com/hp/octane/integrations/dto/executor/ExecutorDTOTests.java, integrations-sdk/src/main/java/com/hp/octane/integrations/services/tasking/TasksProcessorImpl.java, integrations-sdk/src/main/java/com/hp/octane/integrations/spi/CIPluginServices.java, integrations-sdk/src/main/java/com/hp/octane/integrations/spi/CIPluginServicesBase.java
1.fix in test connection with exist credentials
2.adding message for response in executor connectivity method
3.fix code review issue
=> test connection of scm repository

integrations-dto/pom.xml, integrations-dto/src/main/java/com/hp/octane/integrations/dto/executor/DiscoveryInfo.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/executor/impl/DiscoveryInfoImpl.java, integrations-sdk/pom.xml, pom.xml
extending DiscoveryInfo to include executorLogicalName + updating version
=> extending DiscoveryInfo to include executorLogicalName + updating version

integrations-dto/src/main/java/com/hp/octane/integrations/dto/general/CIServerInfo.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/general/impl/CIServerInfoImpl.java
defect #443021 : expose jenkins user + Octane user/APIKey for DevOps Admin
=> expose jenkins user + Octane user/APIKey for DevOps Admin

integrations-sdk/src/main/java/com/hp/octane/integrations/services/bridge/BridgeServiceImpl.java
defect #443021 :  
expose jenkins user + Octane user/APIKey for DevOpsAdmin - adding implementation
=> expose jenkins user + Octane user/APIKey for DevOpsAdmin - adding implementation

integrations-sdk/src/main/java/com/hp/octane/integrations/services/bridge/BridgeServiceImpl.java
defect #443021 : expose jenkins user + Octane user/APIKey for DevOpsAdmin - fix potential null pointer
=> expose jenkins user + Octane user/APIKey for DevOps Admin - fix potential null pointer

README.md, integrations-dto/src/main/java/com/hp/octane/integrations/dto/general/CIServerInfo.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/general/CIServerTypes.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/general/impl/CIServerInfoImpl.java, integrations-dto/src/test/java/com/hp/octane/integrations/dto/DTOFactoryTest.java, integrations-sdk/pom.xml, integrations-sdk/src/main/java/com/hp/octane/integrations/api/TestsService.java, integrations-sdk/src/main/java/com/hp/octane/integrations/services/bridge/BridgeServiceImpl.java, integrations-sdk/src/main/java/com/hp/octane/integrations/services/tests/TestsServiceImpl.java, integrations-sdk/src/main/java/com/hp/octane/integrations/spi/CIPluginServices.java, integrations-sdk/src/main/java/com/hp/octane/integrations/spi/CIPluginServicesBase.java, integrations-sdk/src/test/java/com/hp/octane/integrations/dto/StatusInfoTest.java, pom.xml
Enable reporting of any type of CI server
=> Enable reporting of any type of CI server

README.md
=> Links to CI plugins point to old org

integrations-dto/src/main/java/com/hp/octane/integrations/dto/DTOFactory.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/entities/Entity.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/entities/EntityList.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/entities/OctaneBulkException.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/entities/OctaneException.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/entities/ResponseEntityList.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/entities/impl/DTOEntityProvider.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/entities/impl/EntityImpl.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/entities/impl/EntityListImpl.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/entities/impl/OctaneBulkExceptionImpl.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/entities/impl/OctaneExceptionImpl.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/entities/impl/ResponseEntityListImpl.java, integrations-dto/src/test/java/com/hp/octane/integrations/dto/general/EntityDTOTests.java, integrations-sdk/src/main/java/com/hp/octane/integrations/OctaneSDK.java, integrations-sdk/src/main/java/com/hp/octane/integrations/api/ConfigurationService.java, integrations-sdk/src/main/java/com/hp/octane/integrations/api/EntitiesService.java, integrations-sdk/src/main/java/com/hp/octane/integrations/services/configuration/ConfigurationServiceImpl.java, integrations-sdk/src/main/java/com/hp/octane/integrations/services/entities/EntitiesServiceImpl.java, integrations-sdk/src/main/java/com/hp/octane/integrations/services/entities/QueryHelper.java
user story #651006 : [Tech] [UFT integration]Move common logic related to UFT integration to sdk - Moving CRUD operations to SDK
=> Moving CRUD operations to SDK

integrations-dto/src/main/java/com/hp/octane/integrations/dto/entities/Entity.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/entities/EntityConstants.java, integrations-dto/src/main/java/com/hp/octane/integrations/dto/entities/impl/EntityImpl.java, integrations-sdk/src/main/java/com/hp/octane/integrations/util/Constants.java
user story #651006 : [Tech] [UFT integration]Move common logic related to UFT integration to sdk
=> user story #651006 : Move common logic related to UFT integration to sdk

integrations-sdk/pom.xml, integrations-sdk/src/main/java/com/hp/octane/integrations/exceptions/OctaneBulkException.java, integrations-sdk/src/main/java/com/hp/octane/integrations/exceptions/OctaneRestException.java, integrations-sdk/src/main/java/com/hp/octane/integrations/services/entities/EntitiesServiceImpl.java, integrations-sdk/src/main/java/com/hp/octane/integrations/services/entities/QueryHelper.java, integrations-sdk/src/main/java/com/hp/octane/integrations/uft/UftTestUtil.java, integrations-sdk/src/main/java/com/hp/octane/integrations/util/CIPluginSDKUtils.java, integrations-sdk/src/main/java/com/hp/octane/integrations/util/Constants.java, integrations-sdk/src/main/java/com/hp/octane/integrations/util/SdkConstants.java, integrations-sdk/src/main/java/com/hp/octane/integrations/util/SdkStringUtils.java
1.Creating SdkStringUtils
2.Moving UftTestUtils with dependencies
=> user story #651006 : [Tech] [UFT integration]Move common logic related to UFT integration to sdk

integrations-sdk/src/main/java/com/hp/octane/integrations/services/bridge/BridgeServiceImpl.java
adding error handler to prevent silent bridge startup thread reject
=> Yuri bridge start

integrations-sdk/src/main/java/com/hp/octane/integrations/util/SdkHttpStatus.java
user story #651006 : [UFT integration]Move common logic related to UFT integration to sdk - moving SdkHttpStatus
=> Move common logic related to UFT integration to sdk - moving SdkHttpStatus

integrations-sdk/src/main/java/com/hp/octane/integrations/util/SdkStringUtils.java
user story #651006 : [UFT integration]Move common logic related to UFT integration to sdk - extending SdkStringUtils
=> extending SdkStringUtils

integrations-sdk/src/main/java/com/hp/octane/integrations/OctaneSDK.java, integrations-sdk/src/main/java/com/hp/octane/integrations/services/bridge/BridgeServiceImpl.java, integrations-sdk/src/main/java/com/hp/octane/integrations/services/configuration/ConfigurationServiceImpl.java, integrations-sdk/src/main/java/com/hp/octane/integrations/services/entities/EntitiesServiceImpl.java, integrations-sdk/src/main/java/com/hp/octane/integrations/services/events/EventsServiceImpl.java, integrations-sdk/src/main/java/com/hp/octane/integrations/services/logs/LogsServiceImpl.java, integrations-sdk/src/main/java/com/hp/octane/integrations/services/rest/RestServiceImpl.java, integrations-sdk/src/main/java/com/hp/octane/integrations/services/tests/TestsServiceImpl.java, pom.xml
- added Jacoco coverage setup (run with profile `jacoco-coverage` to get the coverage report)
- explicitly stated Maven plugin's version so have a predictable build
- improved internal SDK's logging
=> SDK code quality improvements

integrations-sdk/pom.xml, integrations-sdk/src/main/java/com/hp/octane/integrations/services/rest/RestClientImpl.java
Octane's rest client should handle cookies (security cookie, specifically) according to RFC-6265
=> handling cookies domain as per RFC-6265

integrations-sdk/src/main/java/com/hp/octane/integrations/services/vulnerabilities/ssc/SscProjectConnector.java
fix for getting only new issues
=> user story#690331 tech : Octane SDK - expose vulnerabilities API in Octane SDK  -  show only new issues

integrations-sdk/src/main/java/com/hp/octane/integrations/services/vulnerabilities/IssuesFileSerializer.java, integrations-sdk/src/main/java/com/hp/octane/integrations/services/vulnerabilities/PackIssuesToSendToOctane.java, integrations-sdk/src/main/java/com/hp/octane/integrations/services/vulnerabilities/SSCHandler.java, integrations-sdk/src/main/java/com/hp/octane/integrations/services/vulnerabilities/VulnerabilitiesServiceImpl.java, integrations-sdk/src/test/java/com/hp/octane/integrations/services/vulnerabilities/PackIssuesToSendToOctaneTest.java
plugin side - Extended data will be calculated in the plugin – only for "missed" entities
Signed-off-by: shmaya <daniel.shmaya@microfocus.com>
=> user story #768088 : [DevSecOps] - plugin side - Extended data

integrations-sdk/pom.xml, integrations-sdk/src/test/java/com/hp/octane/integrations/services/vulnerabilities/ExistingIssuesInOctaneTest.java, integrations-sdk/src/test/java/com/hp/octane/integrations/services/vulnerabilities/ExpectedPushToOctane.java, integrations-sdk/src/test/java/com/hp/octane/integrations/services/vulnerabilities/IssuesValidate.java, integrations-sdk/src/test/java/com/hp/octane/integrations/services/vulnerabilities/OctaneInput.java, integrations-sdk/src/test/java/com/hp/octane/integrations/services/vulnerabilities/PackIssuesToSendToOctaneTest.java, integrations-sdk/src/test/java/com/hp/octane/integrations/services/vulnerabilities/SSCHandlerTest.java, integrations-sdk/src/test/java/com/hp/octane/integrations/services/vulnerabilities/SSCInput.java, integrations-sdk/src/test/java/com/hp/octane/integrations/services/vulnerabilities/SSCIntegrationTest.java, integrations-sdk/src/test/java/com/hp/octane/integrations/services/vulnerabilities/SSCTestUtils.java, integrations-sdk/src/test/java/com/hp/octane/integrations/services/vulnerabilities/SscProjectConnectorPagingTest.java, integrations-sdk/src/test/java/com/hp/octane/integrations/services/vulnerabilities/VulnerabilitiesServiceFunctionalityTest.java, integrations-sdk/src/test/java/com/hp/octane/integrations/services/vulnerabilities/VulnerabilitiesServicePluginServicesTest.java, integrations-sdk/src/test/java/com/hp/octane/integrations/testhelpers/RestServerSimulator.java, integrations-sdk/src/test/java/com/hp/octane/integrations/testhelpers/SSCServerSimulator.java
Integration Tests for SSC scenarios.
=> Quality Story#752030: Automation - Fortify SSC Update Support

integrations-sdk/src/main/java/com/hp/octane/integrations/services/vulnerabilities/sonar/SonarToOctaneIssueUtil.java
sonar vulnerability defect fix
=> defect #809001: Vulnerability doc view- External link is not correct

integrations-sdk/src/main/java/com/hp/octane/integrations/services/vulnerabilities/fod/FODServiceImpl.java, integrations-sdk/src/main/java/com/hp/octane/integrations/services/vulnerabilities/fod/FODValuesConverter.java, integrations-sdk/src/main/java/com/hp/octane/integrations/services/vulnerabilities/fod/dto/FodConnectionFactory.java
External link is missing.
delay between all-data requests.
=> external link + delay between all-data requests

integrations-sdk/src/main/java/com/hp/octane/integrations/services/vulnerabilities/sonar/SonarToOctaneIssueUtil.java
converting date from sonar server date to UTC in the plugin.
=> defect #1011068: vulnerabilities baseline date is incorrect 

integrations-sdk/src/main/java/com/hp/octane/integrations/services/configurationparameters/SCMRestAPIParameter.java, integrations-sdk/src/main/java/com/hp/octane/integrations/services/configurationparameters/factory/ConfigurationParameterFactory.java, integrations-sdk/src/main/java/com/hp/octane/integrations/services/scmdata/SCMDataServiceImpl.java
… event
Add parameter SCM_REST_API to disable Rest API usage
=> Add parameter SCM_REST_API to disable Rest API usage
